RegexPlayground.UI/Controllers/HomeController.cs
using System.Web.Mvc;

namespace RegexPlayground.UI.Controllers
{
    public class HomeController : Controller
    {
        // GET: /Home/
        public ActionResult Index()
        {
            return View();
        }

    }
}

RegexPlayground.UI/Controllers/RiddleController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using RegexPlayground.Core;
using RegexPlayground.Infrastructure;

namespace RegexPlayground.UI.Controllers
{
	public class RiddleController : Controller
	{
		private readonly IRiddleRepository _riddleRepository;

		public RiddleController() : this(new RiddleRepository()) {}

		public RiddleController(IRiddleRepository repository)
		{
			_riddleRepository = repository;
		}

		public ViewResult Index()
		{
			return View();
		}

		public PartialViewResult GetRiddle()
		{
			Riddle riddle = _riddleRepository.GetRandom();
			return PartialView("_Riddle", riddle);
		}

		[HttpPost]
		public JsonResult TestRiddle(Guid id, string pattern)
		{
			Riddle selectedRiddle = _riddleRepository.GetById(id);
			RiddleResult riddleResult = selectedRiddle.Evaluate(pattern);

			return Json(new
				{
					FailedResults = riddleResult.FailedClues.Select(c => c.GetHashCode()).ToArray(),
					SucceededResults = riddleResult.SuccessfulClues.Select(c => c.GetHashCode()).ToArray()
				});
		}
	}
}

RegexPlayground.UI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

<h2>Welcome</h2>
<p>@Html.ActionLink("Start","Index","Riddle")</p>

RegexPlayground.UI/Views/Riddle/Index.cshtml
@model RegexPlayground.Core.Riddle

@{ ViewBag.Title = "Play"; }

@{ Html.RenderAction("GetRiddle", "Riddle"); }

RegexPlayground.UI/Views/Riddle/_Riddle.cshtml
@model RegexPlayground.Core.Riddle

<div class="riddleContainer">
	<table class="riddle">
		@foreach (var clue in Model.Clues) {
			<tr>
				<td class="icon">@Html.Raw(clue.ShouldMatch ? "<span class=\"icon shouldMatch\"></span>" : "&nbsp;")</td>
				<td>@clue.Prompt</td>
				<td class="icon"><span class="icon clueResult result-indeterminate" id="@clue.GetHashCode()"></span></td>
			</tr>
		}
	</table>
	<form action="@Url.Action("TestRiddle", "Riddle")" method="post">
		@Html.HiddenFor(r => r.Id)
		<label for="pattern"><input id="pattern" name="pattern" placeholder="Type your answer here" type="text" /></label>
		<button type="submit"><span class="btn">Check</span></button>
	</form>
	<ol class="priorPatterns"></ol>
</div>

RegexPlayground.UI/Views/Shared/_Layout.cshtml
<!doctype html>
<html class="no-js" lang="en">

<head>
	<meta charset="utf-8">
	
	<title>RegEx Playground|@ViewBag.Title</title>
	<meta name="description" content="">
	<meta name="author" content="">

	<link rel="stylesheet" href="@Url.Content("~/css/boilerplate.css")">
	<link rel="stylesheet" href="@Url.Content("~/css/riddles.css")">
	<script src="@Url.Content("~/js/modernizr-1.7.min.js")"></script>
</head>

<body>

	<header>
		<h1>Regex Riddles</h1>
		<nav>
			<ul>
				<li><a href="@Url.Action("Index", "Riddle")">Play</a></li>
			</ul>
		</nav>
	</header>

	<div id="content">
		@RenderBody()
	</div>

	<script src="@Url.Content("~/js/yepnope.1.0.1-min.js")"></script>
	<script>

		yepnope([{
			load: [
				'http://code.jquery.com/jquery-1.5.2.min.js'
			],
			complete: function () {
				$(function () {
					$('form').submit(function () {
						var form = $(this);

						$.ajax({
							url: form.attr('action'),
							type: form.attr('method'),
							data: form.serialize(),
							success: function (data) {
								var container = form.parents('.riddleContainer');

								$('.clueResult', container).removeClass('result-success').removeClass('result-failure');

								var failures = data.FailedResults;
								var successes = data.SucceededResults;

								var successesCount = successes.length;
								var totalCount = successesCount + failures.length;

								for (var failureIndex in failures) {
									$('#' + failures[failureIndex]).addClass('result-failure');
								}

								for (var successIndex in successes) {
									$('#' + successes[successIndex]).addClass('result-success');
								}

								$('.priorPatterns', container).trigger('regexRiddles:addPriorPattern', [$('#pattern').val(), successesCount, totalCount]);
							}
						});

						return false;
					});

					$('.priorPatterns').bind('regexRiddles:addPriorPattern', function (ev, pattern, successes, total) {
						$('<li>' + pattern + ' (' + successes + ' of ' + total + ')</li>').prependTo($(this));
					});

					$('#pattern').focus();
				});
			}
		}]);

	</script>

</body>

</html>